# Generated by Django 6.0.7 on 2026-07-09 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Cliente')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(max_length=50, verbose_name='Teléfono')),
                ('codigo_cliente', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Código de Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ComprobanteFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Tipo de Comprobante')),
                ('prefijo', models.CharField(max_length=10, unique=True, verbose_name='Prefijo (ej: B01)')),
                ('secuencia_actual', models.IntegerField(default=0, verbose_name='Secuencia Actual')),
                ('secuencia_maxima', models.IntegerField(default=99999999, verbose_name='Secuencia Máxima')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ncf_asignado', models.CharField(blank=True, max_length=30, null=True, verbose_name='NCF Asignado')),
                ('numero_factura', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Número de Factura')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Emisión')),
                ('estado', models.CharField(choices=[('PAGADA', 'Pagada'), ('PENDIENTE', 'Pendiente'), ('ANULADA', 'Anulada')], default='PENDIENTE', max_length=20)),
                ('tasa_cambio', models.DecimalField(decimal_places=2, default=4120.5, max_digits=10, verbose_name='Tasa de Cambio (TRM)')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='facturacion.cliente')),
                ('comprobante_fiscal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='facturacion.comprobantefiscal')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto', models.CharField(max_length=255, verbose_name='Concepto de Servicio')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio Unitario')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='facturacion.factura')),
            ],
        ),
    ]
